### ISSUE TITLE
[Bug]: Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled 

### ISSUE THREAD

**Issue by JamasChuang94** [Aloereed/stable-diffusion-webui-arc-directml#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):

### Steps to reproduce the problem

1. Run  webui-user.bat

### What should have happened?

No error

### Commit where the problem happens

No

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ee3d3904c327031ed193a1e6d8472c3eed9409c7
Installing requirements for Web UI
Launching Web UI with arguments: --opt-sub-quad-attention --disable-nan-check
Thank you for helping to bring diversity to the graphics card market.
Warning: k_diffusion not found at path C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\repositories\k-diffusion\k_diffusion\sampling.py
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\sd_models.py", line 15, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\sd_disable_initialization.py", line 1, in <module>
    import ldm.modules.encoders.modules
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 3, in <module>
    import kornia
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\__init__.py", line 11, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\augmentation\__init__.py", line 1, in <module>
    from kornia.augmentation._2d import (
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\augmentation\_2d\__init__.py", line 3, in <module>
    from kornia.augmentation._2d.mix import *
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\augmentation\_2d\mix\__init__.py", line 1, in <module>
    from kornia.augmentation._2d.mix.cutmix import RandomCutMix, RandomCutMixV2
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\augmentation\_2d\mix\cutmix.py", line 7, in <module>
    from kornia.augmentation._2d.mix.base import MixAugmentationBase, MixAugmentationBaseV2
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\augmentation\_2d\mix\base.py", line 10, in <module>
    from kornia.geometry.boxes import Boxes
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\geometry\boxes.py", line 582, in <module>
    class Boxes3D:
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_script.py", line 1323, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_recursive.py", line 47, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
RuntimeError:

aten::pad(Tensor self, int[] pad, str mode="constant", float? value=None) -> Tensor:
Expected a value of type 'List[int]' for argument 'pad' but instead found type 'Tensor (inferred)'.
Inferred the value for argument 'pad' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\devices.py", line 243
def pad(input, pad, mode='constant', value=None):
    if input.dtype == torch.float16 and input.device.type == 'privateuseone':
        return _pad(input.float(), pad, mode, value).type(input.dtype)
               ~~~~ <--- HERE
    else:
        return _pad(input, pad, mode, value)
'pad' is being compiled since it was called from 'convert_points_to_homogeneous'
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\geometry\conversions.py", line 199
        raise ValueError(f"Input must be at least a 2D tensor. Got {points.shape}")

    return torch.nn.functional.pad(points, [0, 1], "constant", 1.0)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
'convert_points_to_homogeneous' is being compiled since it was called from 'transform_points'
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\geometry\linalg.py", line 189
    trans_01 = torch.repeat_interleave(trans_01, repeats=points_1.shape[0] // trans_01.shape[0], dim=0)
    # to homogeneous
    points_1_h = convert_points_to_homogeneous(points_1)  # BxNxD+1
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    # transform coordinates
    points_0_h = torch.bmm(points_1_h, trans_01.permute(0, 2, 1))
'transform_points' is being compiled since it was called from '_transform_boxes'
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\geometry\boxes.py", line 53
        )

    transformed_boxes: torch.Tensor = transform_points(M, points)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    transformed_boxes = transformed_boxes.view_as(boxes)
    return transformed_boxes
'_transform_boxes' is being compiled since it was called from 'Boxes3D.transform_boxes'
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\kornia\geometry\boxes.py", line 897
        # Due to some torch.jit.script bug (at least <= 1.9), you need to pass all arguments to __init__ when
        # constructing the class from inside of a method.
        transformed_boxes = _transform_boxes(self._data, M)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        if inplace:
            self._data = transformed_boxes
```

**Comment by Aloereed** [comment]
check here.
[issues/2](https://github.com/Aloereed/stable-diffusion-webui-arc-directml/issues/2#issuecomment-1502778441)

**Comment by JamasChuang94** [comment]
> 检查这里。 [问题/2](https://github.com/Aloereed/stable-diffusion-webui-arc-directml/issues/2#issuecomment-1502778441)
Doesn't work
The solution is to comment the line  torch.nn.functional.pad = pad in stable-diffusion-webui-arc-directml\modules\devices.py
After the comment, only the original error in the second half is missing, but the same error in the front
I get the following error：

```Shell
venv "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ee3d3904c327031ed193a1e6d8472c3eed9409c7
Installing requirements for Web UI
Launching Web UI with arguments: --opt-sub-quad-attention --disable-nan-check
Thank you for helping to bring diversity to the graphics card market.
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\modules\sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\pytorch_lightning\__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\pytorch_lightning\callbacks\progress\__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File "C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\pytorch_lightning\callbacks\progress\rich_progress.py", line 20, in <module>
    from torchmetrics.utilities.imports import _compare_version
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (C:\Users\Jamas\Desktop\SD\stable-diffusion-webui-arc-directml\venv\lib\site-packages\torchmetrics\utilities\imports.py)`
```

**Comment by Aloereed** [comment]
check [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11648#issuecomment-1623200571) then.
