### ISSUE TITLE
[Bug]: Error on first start

### ISSUE THREAD

**Issue by gmbhneo** [Aloereed/stable-diffusion-webui-arc-directml#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I get an error upon first start:

Traceback (most recent call last):
  File "C:\A1111\stable-diffusion-webui-arc-directml\launch.py", line 353, in <module>
    start()
  File "C:\A1111\stable-diffusion-webui-arc-directml\launch.py", line 344, in start
    import webui
  File "C:\A1111\stable-diffusion-webui-arc-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "C:\A1111\stable-diffusion-webui-arc-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\A1111\stable-diffusion-webui-arc-directml\modules\shared.py", line 9, in <module>
    import gradio as gr
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\components.py", line 34, in <module>
    from gradio import media_data, processing_utils, utils
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\processing_utils.py", line 23, in <module>
    from gradio import encryptor, utils
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\utils.py", line 416, in <module>
    class AsyncRequest:
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\utils.py", line 436, in AsyncRequest
    client = httpx.AsyncClient()
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\httpx\_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\httpx\_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

### Steps to reproduce the problem

Just install as described and run the bin.

### What should have happened?

Webui should start normally

### Commit where the problem happens

-

### Command Line Arguments

```Shell
-
```

### List of extensions

-

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\A1111\stable-diffusion-webui-arc-directml\launch.py", line 353, in <module>
    start()
  File "C:\A1111\stable-diffusion-webui-arc-directml\launch.py", line 344, in start
    import webui
  File "C:\A1111\stable-diffusion-webui-arc-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "C:\A1111\stable-diffusion-webui-arc-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\A1111\stable-diffusion-webui-arc-directml\modules\shared.py", line 9, in <module>
    import gradio as gr
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\components.py", line 34, in <module>
    from gradio import media_data, processing_utils, utils
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\processing_utils.py", line 23, in <module>
    from gradio import encryptor, utils
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\utils.py", line 416, in <module>
    class AsyncRequest:
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\gradio\utils.py", line 436, in AsyncRequest
    client = httpx.AsyncClient()
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\httpx\_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\httpx\_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "C:\A1111\stable-diffusion-webui-arc-directml\venv\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```

**Comment by moyilong** [comment]
try install httpx to 0.24.1?
run in venv:
```bash
pip install httpx==0.24.1
```

**Comment by xysnailt** [comment]
I got the same error

**Comment by gmbhneo** [comment]
> try install httpx to 0.24.1? run in venv:
> 
> ```shell
> pip install httpx==0.24.1
> ```

Still got the same error after doing this.

**Comment by gmbhneo** [comment]
Got this fixed by adding the following line to "requirements_versions.txt" in the main directory:

`httpx==0.24.1`

So now it looks like: 

`blendmodes==2022
httpx==0.24.1
transformers==4.25.1
accelerate==0.12.0
basicsr==1.4.2
gfpgan==1.3.8
gradio==3.16.2
numpy==1.23.3`.....
